### ISSUE TITLE
Load Scene doesn't load two times

### ISSUE THREAD

**Issue by AuxPort66** [Horizons-Games/Axolotl-Engine#468]
The scene doesn't load a second time on game. Only load the first time.
We use the same function that loadScene in Engine, but in Engine Works perfectly.

https://app.clickup.com/t/865cfvjkb <- ClickUp Task

**Comment by gerard-queralt** [comment]
Summary of my findings so far:
- In broad terms the issue seems to be this loop ([link to source file](https://github.com/Horizons-Games/Axolotl-Engine/blob/develop/Source/Modules/ModuleScene.cpp#L488))
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/79362519/966dee8f-3f4e-4dbd-a2e3-2a48e5eae6e7)
    - As a reminder, this loop is used to "load" GameObjects. What this actually means is that it creates the components and reads the necessary resources for each of them. This is performed after a previous loop used to instantiate the GameObjects, and a call to initialize the vectors in the scene (which some of the components require).
- As reported, first load works just fine. Second one, however, appears to have massive leaks, if I'm reading the profiling right.
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/79362519/432c2bd0-0585-46ab-afa6-d7759d6afc1f)
    - This is the memory usage after approximately 270 GameObjects have been loaded; you can see that it has doubled, which, to reiterate, doesn't happen in the first load. This scene has more than 4700 GameObjects, so eventualy it hangs.
- Heap size difference after these 270 iterations
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/79362519/89ba4168-6a2f-4f21-909b-f940a9af67a6)
- Main culprit seems to be allocation of `unsigned char[]`
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/79362519/c2667044-a6f7-4b97-bc38-d26d0ca1f7a7)
- Upon further inspection, these seem to be allocated when importing textures
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/79362519/a8b57507-7a66-4bdf-81a6-b366d7d58115)

Will continue later.
