### ISSUE TITLE
Bix attack not hitting the enemies

### ISSUE THREAD

**Issue by markmeliaa** [Horizons-Games/Axolotl-Engine#517]
When the raycast of Bix's attack is thrown, it no longer detects the enemies, only Bix herself. This is something that changed recently, as the branch `GamePlay/reorganize-scripts` has the attack working correctly, but `game-programming` and `develop` doesn't.

**Comment by gerard-queralt** [comment]
I've been checking this by adding a bunch of logs to the Quadtree set-up and the Raycast hits. Here's a log file of the current state in develop:
[Axolotl-develop.log](https://github.com/Horizons-Games/Axolotl-Engine/files/11857425/Axolotl.log)
It would appear that the issue come from two different merges:
- First, my changes to the de-serialization process (#476), where I changed an unordered map for a regular one:
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/79362519/732a137e-d595-4580-a1a1-5bdb9472f59d)
- Second, #496, where objects that don't have a Drawable component are not added to either the Quadtree or the non-static objects vector, which means they are not considered for the Raycast calculation.

I don't understand how either of these changes may contribute to the error, but reverting them (changing back the map and hard-coding the `IsRenderable` to always return `true`) fixes it. Here's the updated log:
[Axolotl-hardfix.log](https://github.com/Horizons-Games/Axolotl-Engine/files/11857447/Axolotl.log)
You can see that the log says `hit returning: DRONE.wingRight.055_0`, which is what we would expect.

Keep the change to the map reverted, but re-applying the filtering done using `IsRenderable`, I've noticed that the condition to filter a given Game Object in the raycast appears to be true only when the object hit is a direct descendant of the filtering one, but is false if it's further down in the hierarchy. This is fixed in 1aa9cad, and this is the resulting log:
[Axolotl-fix-raycast.log](https://github.com/Horizons-Games/Axolotl-Engine/files/11857501/Axolotl.log)

There, Bix's meshes are correctly discarded. However, I still don't understand how those two changes are causing this issue in the first place.

**Comment by gerard-queralt** [comment]
As said in the linked PR, the reason those changes unearthed this issue is because they affected the order in which elements were hit by the raycast. In the order it was before, it ended up correctly filtering, but that was pure chance. Thanks to @AuxPort66 for the help understanding it.
