### ISSUE TITLE
Scheduleable class breaks the engine sometimes when loading a scene

### ISSUE THREAD

**Issue by markmeliaa** [Horizons-Games/Axolotl-Engine#777]
<img width="1120" alt="image" src="https://github.com/Horizons-Games/Axolotl-Engine/assets/82601780/ba4f2ad1-7a75-4b38-beb8-0b69c900fd10">

**Comment by gerard-queralt** [comment]
Since the teachers basically told us to not chase low-repro bugs, I'll take them on their word and mark this as "won't fix". If someone want to take up where I left, there's a logging improvemtn and some crash logs in this branch: https://github.com/Horizons-Games/Axolotl-Engine/tree/investigate-schedulable-crash

**Comment by gerard-queralt** [comment]
Actually nevermind, figured it out I think. Fix is on the way 😉
